# Generated by Django 2.0.7 on 2018-07-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dati', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='option_four',
            field=models.CharField(default='not', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_one',
            field=models.CharField(default='not', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_three',
            field=models.CharField(default='not', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option_twe',
            field=models.CharField(default='not', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
