# Generated by Django 2.0.7 on 2018-07-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dati', '0002_auto_20180718_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.CharField(max_length=25),
        ),
    ]
